Segyul/model generation
jinensetpal/connector-classification pull request #2
Opened 2021-10-30 17:00 UTC by Paaaark

Model Generation

2021-11-01 03:35 UTC, SpideR1sh1 approved these changes

2021-11-01 20:19 UTC, jinensetpal requested changes
@Paaaark please remove the test and training dataset binaries, rest's perfect

2021-11-01 23:24 UTC, jinensetpal approved these changes

2021-11-06 03:37 UTC, saadsheriff approved these changes

2021-11-06 03:37 UTC, merged